require("tests.test_harness")

describe("distract.manifests cat definition", function()
  local cat = require("distract.manifests.cat")

  it("has valid metadata and spritesheet properties", function()
    assert.are.same("cat", cat.name)
    assert.are.same("sprite", cat.asset_type)
    assert.are.same("idle", cat.initial_state)
    assert.is_not_nil(cat.spritesheet.path)
    assert.are_equal(48, cat.spritesheet.frame_width)
    assert.are_equal(48, cat.spritesheet.frame_height)
    assert.are_equal(4, cat.spritesheet.columns)
    assert.are_equal(1, cat.spritesheet.rows)

  end)

  it("defines all required behavioral states", function()
    assert.is_not_nil(cat.states.idle)
    assert.is_not_nil(cat.states.walk)
    assert.is_not_nil(cat.states.walk_fast)
    assert.is_not_nil(cat.states.jump)
    assert.is_not_nil(cat.states.yawn)
    assert.is_not_nil(cat.states.sleep)
  end)

  it("defines all custom action triggers", function()
    assert.is_not_nil(cat.custom_actions.jump)
    assert.are.same("jump", cat.custom_actions.jump.target_state)
    assert.is_not_nil(cat.custom_actions.yawn)
    assert.are.same("yawn", cat.custom_actions.yawn.target_state)
    assert.is_not_nil(cat.custom_actions.sleep)
    assert.is_not_nil(cat.custom_actions.wake)
    assert.is_not_nil(cat.custom_actions.sit)
  end)
end)

describe("distract.manifests crab definition", function()
  local crab = require("distract.manifests.crab")

  it("has valid metadata and initial state", function()
    assert.are.same("crab", crab.name)
    assert.are.same("procedural", crab.asset_type)
    assert.are.same("idle", crab.initial_state)
  end)

  it("defines all required behavioral states", function()
    assert.is_not_nil(crab.states.idle)
    assert.is_not_nil(crab.states.walk)
    assert.is_not_nil(crab.states.walk_fast)
    assert.is_not_nil(crab.states.clip_claws)
    assert.is_not_nil(crab.states.burrow)
    assert.is_not_nil(crab.states.sleep)
  end)

  it("defines all custom action triggers", function()
    assert.is_not_nil(crab.custom_actions.clip)
    assert.are.same("clip_claws", crab.custom_actions.clip.target_state)
    assert.is_not_nil(crab.custom_actions.burrow)
    assert.are.same("burrow", crab.custom_actions.burrow.target_state)
    assert.is_not_nil(crab.custom_actions.sleep)
    assert.is_not_nil(crab.custom_actions.wake)
    assert.is_not_nil(crab.custom_actions.walk)
  end)
end)

describe("distract.manifests sun definition", function()
  local sun = require("distract.manifests.sun")

  it("has valid metadata and initial state", function()
    assert.are.same("sun", sun.name)
    assert.are.same("procedural", sun.asset_type)
    assert.are.same("shining", sun.initial_state)
  end)

  it("defines all required celestial states", function()
    assert.is_not_nil(sun.states.shining)
    assert.is_not_nil(sun.states.rising)
    assert.is_not_nil(sun.states.setting)
    assert.is_not_nil(sun.states.eclipse)
    assert.is_not_nil(sun.states.flare)
  end)

  it("defines all custom action triggers", function()
    assert.is_not_nil(sun.custom_actions.eclipse)
    assert.are.same("eclipse", sun.custom_actions.eclipse.target_state)
    assert.is_not_nil(sun.custom_actions.rise)
    assert.are.same("rising", sun.custom_actions.rise.target_state)
    assert.is_not_nil(sun.custom_actions.set)
    assert.are.same("setting", sun.custom_actions.set.target_state)
    assert.is_not_nil(sun.custom_actions.flare)
    assert.are.same("flare", sun.custom_actions.flare.target_state)
  end)
end)
