require("tests.test_harness")
local distract = require("distract")

describe("distract.plugin user commands", function()
  it("registers all expected Neovim user commands", function()
    local cmds = vim.api.nvim_get_commands({})
    assert.is_not_nil(cmds["DistractStart"])
    assert.is_not_nil(cmds["DistractStop"])
    assert.is_not_nil(cmds["DistractToggle"])
    assert.is_not_nil(cmds["DistractSpawn"])
    assert.is_not_nil(cmds["DistractAction"])
    assert.is_not_nil(cmds["DistractClear"])
    assert.is_not_nil(cmds["DistractStatus"])
  end)

  it("can invoke user commands without unhandled exceptions", function()
    assert.has_no.errors(function()
      vim.cmd("DistractStart")
      vim.cmd("DistractSpawn cat")
      vim.cmd("DistractSpawn crab")
      vim.cmd("DistractSpawn sun")
      vim.cmd("DistractAction jump cat")
      vim.cmd("DistractAction clip crab")
      vim.cmd("DistractAction eclipse sun")
      vim.cmd("DistractStatus")
      vim.cmd("DistractClear")
      vim.cmd("DistractToggle")
      vim.cmd("DistractStop")
    end)
  end)
end)

describe("distract.plugin command completions", function()
  it("DistractSpawn autocompletes available asset names", function()
    local names = distract.get_asset_names()
    assert.is_true(vim.tbl_contains(names, "cat"))
    assert.is_true(vim.tbl_contains(names, "crab"))
    assert.is_true(vim.tbl_contains(names, "sun"))
  end)

  it("DistractAction autocompletes custom actions across assets", function()
    local actions = distract.get_all_actions()
    assert.is_true(vim.tbl_contains(actions, "jump"))
    assert.is_true(vim.tbl_contains(actions, "yawn"))
    assert.is_true(vim.tbl_contains(actions, "clip"))
    assert.is_true(vim.tbl_contains(actions, "burrow"))
    assert.is_true(vim.tbl_contains(actions, "eclipse"))
    assert.is_true(vim.tbl_contains(actions, "rise"))
    assert.is_true(vim.tbl_contains(actions, "set"))
    assert.is_true(vim.tbl_contains(actions, "flare"))
  end)
end)
